### ISSUE TITLE
Tab behaviour has changed in version 3.0.44

### ISSUE THREAD

**Issue by AharonBenCarmela** [koush/vysor.io#496]
Hello,

I installed 3.0.44 (not that I had a choice...) PRO - lifetime license - and together with other issues already reported here, I'm having a problem with the default behaviour of the TAB key on the desktop keyboard.

In previous versions, hitting the TAB key while in an Android text entry box (for example, the one where you type your message in a Whatsapp chat) resulted in the cursor moving to the next item within the application (as tab should do). Now, if you have either the navigation buttons enabled or the title bar is visible, TAB will jump to the menus of Vysor itself (Vysor gains focus regardless of what's in Android). If you disable the navigation bar and the title bar, TAB ends up doing nothing.
Can you please re-enable the default behaviour of TAB or make it at least configurable? I'm using the default mappings:

{
  "themeColor": "#3949AB",
  "mousedown": {
    "1": "KEYCODE_HOME",
    "2": "KEYCODE_BACK"
  },
  "keydown": {
    "ArrowDown": "KEYCODE_DPAD_DOWN",
    "ArrowLeft": "KEYCODE_DPAD_LEFT",
    "ArrowRight": "KEYCODE_DPAD_RIGHT",
    "ArrowUp": "KEYCODE_DPAD_UP",
    "Backspace": "KEYCODE_DEL",
    "Delete": "KEYCODE_FORWARD_DEL",
    "Enter": "KEYCODE_ENTER",
    "Escape": "KEYCODE_BACK",
    "F1": "KEYCODE_MENU",
    "F2": "VYSOR_SHOW_TITLE_BAR",
    "F3": "VYSOR_ENTER_FULLSCREEN",
    "F4": "VYSOR_EXIT_FULLSCREEN",
    "Home": "KEYCODE_HOME",
    "Tab": {
      "keyevent": "KEYCODE_TAB",
      "shiftKey": true
    }
  },
  "navigationBar": {
    "buttons": [
      {
        "class": "fa-chevron-left",
        "event": "KEYCODE_BACK",
        "title": "Back"
      },
      {
        "class": "far fa-circle",
        "event": "KEYCODE_HOME",
        "title": "Home"
      },
      {
        "class": "fa-bars",
        "event": "KEYCODE_APP_SWITCH",
        "title": "Recent Tasks"
      }
    ]
  },
  "titleBar": {
    "buttonGroups": [
      {
        "buttons": [
          {
            "class": "fa-camera",
            "title": "Take Screenshot",
            "event": "VYSOR_SCREENSHOT"
          },
          {
            "class": "fa-video",
            "stopClass": "fa-video-slash fa-spin",
            "stopColor": "red",
            "title": "Record Screen",
            "event": "VYSOR_RECORD_SCREEN"
          }
        ]
      },
      {
        "menuClass": "fa-ellipsis-v",
        "buttons": [
          {
            "class": "fa-headphones",
            "stopColor": "green",
            "title": "Toggle Audio",
            "event": "VYSOR_TOGGLE_AUDIO"
          },
          {
            "class": "fa-wifi",
            "title": "Wireless Mode",
            "event": "VYSOR_WIRELESS_MODE"
          },
          {
            "class": "fa-redo",
            "title": "Rotate Screen",
            "event": "VYSOR_ROTATE_SCREEN"
          },
          {
            "class": "fa-expand",
            "title": "Full Screen",
            "event": "VYSOR_ENTER_FULLSCREEN"
          },
          {
            "class": "fa-power-off",
            "title": "Screen On/Off",
            "event": "KEYCODE_POWER"
          },
          {
            "class": "fa-cog",
            "title": "Settings",
            "event": "VYSOR_OPEN_DEVICE_SETTINGS"
          }
        ]
      }
    ]
  },
  "devices": {
    "example-device-serial": {
      "themeColor": "#AA00FF",
      "keydown": {
        "F3": "KEYCODE_BACK"
      },
      "navigationBar": {
        "buttons": [
          {
            "class": "fa-circle",
            "event": "KEYCODE_HOME",
            "title": "Home"
          }
        ]
      }
    }
  }
}

**Comment by koush** [comment]
Thanks for the bug report. I'll fix this.

**Comment by AharonBenCarmela** [comment]
You're very welcome! I love the application by the way, although I still experience some weirdness (for example, if a URL contains dots and numbers, control-v to Android results in a corrupted string.. but that could be specific to Swiftkey so I haven't opened a bug yet).

**Comment by CCattano** [comment]
Was just about to open a issue for this myself, lol.

Usually I depend on tab to be able to tab over to the send/submit button of my messaging apps so I don't have to take my hands off the keyboard to send a message I've finished typing. I'm excited to see this fixed.

Thanks for all the hard work addressing these issues in such a timely matter @koush !

**Comment by koush** [comment]
Fixed in 3.0.71. Reload the app.

**Comment by crouchingtiger** [comment]
Thanks for the quick updates!

I'm unfortunately getting a double-tab behaviour at this point (it skips over one of the fields). Pixel 2 XL, Android 8.1.x. I can file a proper report later if necessary.

**Comment by koush** [comment]
I’ll double check but I was not seeing that. A specific app to check (preferably one I don’t have to install) would be good.

**Comment by AharonBenCarmela** [comment]
I'm still getting 3.0.67 (branded as 62 for some reason) from vysor.io website and autoupdate.

**Comment by crouchingtiger** [comment]
Updated to 3.0.73 (though the About dialog displays 3.0.67). Video attached of TAB behaviour in the default Contacts app.

 [Video](https://imgur.com/GwJv4Py)

**Comment by CCattano** [comment]
On 3.0.73 as well.

Apologies in advance for the slow low frame-rate gif. I need to find a better screen recorder lol.
![VysorTabFuncTest](https://user-images.githubusercontent.com/47487276/81299763-5400d680-903c-11ea-858e-48965ed36527.gif)

I'm still experiencing the double tab functionality also. This is in Fb Messenger app. It's kind of lost in the low frame rate gif, but when pressing tab for a brief few hundred milliseconds the emoji icon is highlighted with focus then immediately jumps to the send message icon.

The most predominant thing I rely on the tab functionality for is tabbing from the message window to the send message key for my messaging applications. For example my texting app of choice PulseSMS doesn't have any other items in its tab index between the message input field and the send key like Fb Messenger does.

So when I hit tab the focus shifts to the send key for only a couple hundred ms, and then the second tab occurs and places the focus on something else so I can't reach the send key without using my mouse or hitting tab about 6 times to cycle through everything and back to the send message icon.

**Comment by crouchingtiger** [comment]
> Apologies in advance for the slow low frame-rate gif. I need to find a better screen recorder lol.

Why don't you use Vysor's screen recording capabilities? :)

**Comment by CCattano** [comment]
> > Apologies in advance for the slow low frame-rate gif. I need to find a better screen recorder lol.
> 
> Why don't you use Vysor's screen recording capabilities? :)

Oh duh lol. I totally forgot that was available functionality. Good looking out @crouchingtiger!

**Comment by koush** [comment]
I found the issue. Wasn’t happening when the app was running with the debugger open.
