### ISSUE TITLE
Error: stream ended during read for minimum 4 bytes (Google Glass/Wear)

### ISSUE THREAD

**Issue by johny-johnson** [koush/vysor.io#570]
**Describe the bug**
Receive a popup after clicking View saying:
Mirroring Disconnected
Error: stream ended during read for minimum 4 byes

**Attach a Vysor Bug Report Log**
[bug report logs.zip](https://github.com/koush/vysor.io/files/4794721/bug.report.logs.zip)

**To Reproduce**
1. Launch Vysor on desktop
2. Plug in device using usb-c cable
3. Accept allow debug prompt on device
4. Click View on desktop Vysor client

**Expected behavior**
Screen mirroring should start

**Screenshots**
![image](https://user-images.githubusercontent.com/7062759/84941490-7c560900-b0af-11ea-9856-c42241780827.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Vysor Version Pro 3.0.95

**Android (please complete the following information):**
 - Device: Google Glass Enterprise Edition 2
 - OS: Android 8.1.0
 - Vysor Bug Report Link: https://codeload.github.com/gist/c6c16da7434b1a8774585e194415dcc2/zip/1e185436bb6c4105f54fbb89970f7979ff0d168c

**Android Logcat**
[vysor.log](https://github.com/koush/vysor.io/files/4794718/vysor.log)

**Additional context**
N/A

**Comment by Gallardo26** [comment]
Same, facing the same issue since yesterday 17 June.
Was fine up to 16 June.

OS: Windows 10 Pro 1909, Windows 10 Enterprise LTSC 1809
Vysor Pro 3.0.95

Devices: OnePlus 7 Pro latest version (OxygenOS Build 10.3.3.GM21AA) Android 10,
Xiaomi Mi Pad 4 Plus (Android 10 Lineage OS)

Tried both Wireless and Wired method. Same issue.

**Comment by koush** [comment]
@johny-johnson did this used to work on google glass?

I see a video encoder crash in the logcat. Can you take a screenshot of your Vysor encoding settings? You may be using settings that are beyond the capability of glass. Try 25% 500kbps.

**Comment by johny-johnson** [comment]
@koush yes, it used to work on Google Glass.  

Here is a sceeenshot of the encoding settings:
![image](https://user-images.githubusercontent.com/7062759/86172267-183e3680-baec-11ea-9829-965e1a95b924.png)

I tried 25% 500kbps and got the same error. I also tried the following parameters in the settings (while keeping 25% 500kbps):
Decoder - WebAssembly, Native Software, Native Hardware, Native Hardware with fallback 

And for each decoder, I also tried the Force H264 Baseline Profile but in all combinations I got the same error as before.

**Comment by development-1000realities** [comment]
+1 
Same issue occurs on the Vuzix M400 with Vysor 3.0.95

**Comment by koush** [comment]
This seems to be a codec configuration issue. I'll need to add more logging to the Android side to diagnose the issue further.

**Comment by koush** [comment]
Can you attach a bug report? That will have more information, like the screen and encode resolutions.

**Comment by koush** [comment]
nevermind, i see the report.

**Comment by andyosullivan** [comment]
Any update on this? I'm getting the same issue with Google Glass, Enterprise Edition v2.

**Comment by MoacirFB** [comment]
Hi @koush , 

I got the exact same error when trying to connect wirelessly to my phone (Huawei Nova 5T). In my case, the wireless connection seems to be successful, but as soon as I disconnect my phone from the USB port, the _"
_Error: stream ended during read for minimum 4 bytes"__ error occurs. 

If there is any information I can provide that might be of help please let me know.

**Comment by su2353** [comment]
the same problem i get

**Comment by andyosullivan** [comment]
I switched to using scrcpy which works fine with Glass.

**Comment by jhutch44** [comment]
I had same problem.  I disconnected from my VPN and it started working.  I needed to connect wirelessly first, then start VPN.

**Comment by z695101385** [comment]
I had same problem. OS 8.1, android watch

**Comment by koush** [comment]
Investigating

**Comment by koush** [comment]
My investigation leads me to believe this is a Google Glass firmware update issue. I'm seeing if there's a workaround. There were no Vysor releases in June or July. The issue started occurring after the June Glass update:

https://developers.google.com/glass-enterprise/downloads/release-notes

Still looking into workarounds on better codec selection.

**Comment by koush** [comment]
I think this problem is resolved. Vysor was attempting to encode the video at resolutions that were lower than the minimum supported value.
To fix this, update to 3.1.7.

If the problem persists:

1. Open Vysor Settings
2. set the resolution to "Use Recommended Settings" or "50%". "25%" will not work.
3. Save

![Pixel_4](https://user-images.githubusercontent.com/73924/90579326-857c5880-e17a-11ea-9f19-a0a0a2b7f001.png)

Please confirm.

**Comment by edusense-ai** [comment]
Hi! I love Vysor and I'm using the Pro version. Can someone tell me how to get v3.1.7 or above for macOS? I'm facing this issue right now.

Thanks!

**Comment by nirmalpatel** [comment]
Hi! I love Vysor and I'm using the Pro version. Can someone tell me how to get v3.1.7 or above for macOS? I'm facing this issue right now.

Thanks!

**Comment by edusense-ai** [comment]
@koush Persistently facing this issue on my Vysor mac v3.2.31 with Motorola One Fusion+. It has Android 10.

I'm using Vysor Pro but will have to discontinue if this persists, can you please tell me how to fix it? Using the recommended settings does not work.

**Comment by nirmalpatel** [comment]
@koush Persistently facing this issue on my Vysor mac v3.2.31 with Motorola One Fusion+. It has Android 10. I'm using Vysor Pro but will have to discontinue if this persists, can you please tell me how to fix it? Using the recommended settings does not work.

**Comment by koush** [comment]
@nirmalpatel open a new bug with all the relevant information. This original bug was fixed, you're just getting the same general disconnect message.

**Comment by nirmalpatel** [comment]
@koush turns out that revoking USB debugging authorizations of all devices on the Android and then re-authorizing my laptop did the trick. Wireless mirroring working fine for me now. Thanks!

**Comment by Cazpian** [comment]
> @koush turns out that revoking USB debugging authorizations of all devices on the Android and then re-authorizing my laptop did the trick. Wireless mirroring working fine for me now. Thanks!

Hi .. can you post information on how you revoke USB debugging authorization please? I'm currently facing the same disconnect issue regardless of settings ... using Xioami Redmi Note 8 on Android 10 MIUI V12.0.3 and surfacebook one with windows 10.

**Comment by nirmalpatel** [comment]
@Cazpian there is an option for this in the Android Developer Options menu:

![Screenshot_20210128-174415](https://user-images.githubusercontent.com/830400/106137363-9d77ef80-6190-11eb-9edb-d740a057ffce.png)

**Comment by Cazpian** [comment]
Hi @nirmalpatel,

I have tried revoking the authorisation above and reconnecting via usb. This then requests the permission to connect via usb but the problem persists. Vysor either responds with the connection error message above initially (before disconnecting) or if I manage to get a successful connection the error is presented after disconnecting the usb lead. I'm also getting a second vysor window opening on occasion with a view of the phone, but with the default name i.e. REDMI NOTE_8

**Comment by stevegomes** [comment]
This issue seems to be resolved for me.The problem was that I had two different versions of ADB installed on machine, correcting and pointing out the right version solved the issue for me.
