### ISSUE TITLE
Android: Paste Function not working

### ISSUE THREAD

**Issue by ehuezod** [koush/vysor.io#864]
**You must attach a Vysor Bug Report Link**
1. First, trigger the bug.
2. **Leave the window with the bug open.** Do not close it, or the bug data will be lost.
3. To generate a bug report, open the main device window if it is not open already. Click the Bug Report button along the bottom. Please note that this will contain your email address. This is necessary for diagnosing licensing/purchase issues.
4. **ISSUES WITHOUT BUG REPORTS MAY BE IMMEDIATELY CLOSED.** The bug report contains internal logging from the app.

**To Reproduce**
1. Anywhere on the app
2. Press Ctrl+V
3. Paste doesn't happen

**Expected behavior**
It is expected that vysor starts typing what you had on the clipboard

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10.0.18363

**Android (please complete the following information):**
 - Device: FireTV
 - OS: Fire OS 5.2.7.8
 - Vysor Bug Report Link: (when trying to report the bug error code 500 was displayed)

**Additional context**

**Comment by koush** [comment]
Can you tell me if using the paste context menu on a text field works after attempting to paste with CTRL-V?

<img width="680" alt="Screen Shot 2021-07-20 at 8 46 15 AM" src="https://user-images.githubusercontent.com/73924/126354868-b620824c-4da5-443a-9289-92ff18c90cea.png">

**Comment by ehuezod** [comment]
The situation is that, this is happening on Fire OS, the OS used by FireTV devices. You don't have that option available there, but before the last update ctrl+v was working fine.

**Comment by koush** [comment]
Understood. Let me a setting to revert to the previous behavior:

The previous behavior was sending the characters across as keystrokes.
The new behavior was updating the device clipboard and allowing the OS to handle the KEYCODE_PASTE event, which apparently does not work on FireOS.

**Comment by koush** [comment]
Also, please include a generated bug report. I may be able to get the new behavior working if there's something in the log I can fix.

**Comment by ehuezod** [comment]
I created 2, though I'm not sure if the action was caught. 

https://gist.github.com/VysorLogs/43f1ecce36baf1c09c2477637d9a384e
https://gist.github.com/VysorLogs/51b0f6ce494042b632c82fec0f089628

**Comment by koush** [comment]
haha wow. yeah, that's a new one.

```
input websocket java.lang.NoSuchFieldException: KEYCODE_PASTE
java.lang.NoSuchFieldException: KEYCODE_PASTE
	at java.lang.Class.getDeclaredField(Class.java:887)

```

**Comment by woojin58** [comment]
Did you fix the copy paste?

**Comment by woojin58** [comment]
I can't copy and paste, so I can't work.

**Comment by woojin58** [comment]
There is no such option, but ctrl+v worked properly before the last update.

**Comment by woojin58** [comment]
Can I apply the last update? If possible, please let me know how to apply it.

**Comment by koush** [comment]
fixed

**Comment by ehuezod** [comment]
Hi, I just updated to the most recent version but still the ctrl+v isn't working

https://gist.github.com/VysorLogs/cd74155cd82e3f7ab1532801f4ed8774

**Comment by koush** [comment]
Can you uninstall Vysor from the android and then let the desktop app reinstall it? I think I forgot to force an update on this version.

**Comment by ehuezod** [comment]
I just tried it but still no luck. I got different info from the bug report though

https://gist.github.com/VysorLogs/a8455ee150534173a8014dd5db1a1fb8
